package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
public class CoreLoveLook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.add_time
     *
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.rel_href
     *
     */
    private String relHref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.link_type
     *
     */
    private Integer linkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.link_name
     *
     */
    private String linkName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_love_look.id
     *
     * @return the value of core_love_look.id
     *
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_love_look.id
     *
     * @param id the value for core_love_look.id
     *
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_love_look.add_time
     *
     * @return the value of core_love_look.add_time
     *
     * 
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_love_look.add_time
     *
     * @param addTime the value for core_love_look.add_time
     *
     * 
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_love_look.rel_href
     *
     * @return the value of core_love_look.rel_href
     *
     * 
     */
    public String getRelHref() {
        return relHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_love_look.rel_href
     *
     * @param relHref the value for core_love_look.rel_href
     *
     * 
     */
    public void setRelHref(String relHref) {
        this.relHref = relHref == null ? null : relHref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_love_look.link_type
     *
     * @return the value of core_love_look.link_type
     *
     * 
     */
    public Integer getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_love_look.link_type
     *
     * @param linkType the value for core_love_look.link_type
     *
     * 
     */
    public void setLinkType(Integer linkType) {
        this.linkType = linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_love_look.link_name
     *
     * @return the value of core_love_look.link_name
     *
     * 
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_love_look.link_name
     *
     * @param linkName the value for core_love_look.link_name
     *
     * 
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }
}