package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
public class CoreGossip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.type
     *
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.content
     *
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.img_url
     *
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.add_time
     * <p>
     * 
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.star_number
     *
     */
    private Integer starNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_gossip.id
     *
     * @return the value of core_gossip.id
     *
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_gossip.id
     *
     * @param id the value for core_gossip.id
     *
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_gossip.type
     *
     * @return the value of core_gossip.type
     *
     * 
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_gossip.type
     *
     * @param type the value for core_gossip.type
     *
     * 
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_gossip.content
     *
     * @return the value of core_gossip.content
     *
     * 
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_gossip.content
     *
     * @param content the value for core_gossip.content
     *
     * 
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_gossip.img_url
     *
     * @return the value of core_gossip.img_url
     *
     * 
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_gossip.img_url
     *
     * @param imgUrl the value for core_gossip.img_url
     *
     * 
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_gossip.add_time
     *
     * @return the value of core_gossip.add_time
     *
     * 
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_gossip.add_time
     *
     * @param addTime the value for core_gossip.add_time
     *
     * 
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_gossip.star_number
     *
     * @return the value of core_gossip.star_number
     *
     * 
     */
    public Integer getStarNumber() {
        return starNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_gossip.star_number
     *
     * @param starNumber the value for core_gossip.star_number
     *
     * 
     */
    public void setStarNumber(Integer starNumber) {
        this.starNumber = starNumber;
    }
}