package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
public class CoreFieldMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_field_map.field_name
     *
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_field_map.value
     *
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_field_map.text
     *
     */
    private String text;

}