package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

/**
 * @author BlueSkyCarry
 */
@Getter
@Setter
@NoArgsConstructor
public class CoreArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.menu_id
     *
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.title
     *
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.content
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.is_show_title
     *
     */
    private Boolean isShowTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.abstract_msg
     *
     */
    private String abstractMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.create_time
     *
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.update_time
     *
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.is_lock
     *
     */
    private Boolean isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.lock_password
     *
     */
    private String lockPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.is_draft
     *
     */
    private Boolean isDraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.labels
     *
     */
    private String labels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.cust_uri
     *
     */
    private String custUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.comment_type
     *
     */
    private Integer commentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.is_special
     *
     */
    private Boolean isSpecial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.id
     *
     * @return the value of core_article.id
     *
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.id
     *
     * @param id the value for core_article.id
     *
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.menu_id
     *
     * @return the value of core_article.menu_id
     *
     * 
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.menu_id
     *
     * @param menuId the value for core_article.menu_id
     *
     * 
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.title
     *
     * @return the value of core_article.title
     *
     * 
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.title
     *
     * @param title the value for core_article.title
     *
     * 
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.content
     *
     * @return the value of core_article.content
     *
     * 
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.content
     *
     * @param content the value for core_article.content
     *
     * 
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.is_show_title
     *
     * @return the value of core_article.is_show_title
     *
     * 
     */
    public Boolean getIsShowTitle() {
        return isShowTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.is_show_title
     *
     * @param isShowTitle the value for core_article.is_show_title
     *
     * 
     */
    public void setIsShowTitle(Boolean isShowTitle) {
        this.isShowTitle = isShowTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.abstract_msg
     *
     * @return the value of core_article.abstract_msg
     *
     * 
     */
    public String getAbstractMsg() {
        return abstractMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.abstract_msg
     *
     * @param abstractMsg the value for core_article.abstract_msg
     *
     * 
     */
    public void setAbstractMsg(String abstractMsg) {
        this.abstractMsg = abstractMsg == null ? null : abstractMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.create_time
     *
     * @return the value of core_article.create_time
     *
     * 
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.create_time
     *
     * @param createTime the value for core_article.create_time
     *
     * 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.update_time
     *
     * @return the value of core_article.update_time
     *
     * 
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.update_time
     *
     * @param updateTime the value for core_article.update_time
     *
     * 
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.is_lock
     *
     * @return the value of core_article.is_lock
     *
     *
     */
    public Boolean getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.is_lock
     *
     * @param isLock the value for core_article.is_lock
     *
     * 
     */
    public void setIsLock(Boolean isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.lock_password
     *
     * @return the value of core_article.lock_password
     *
     * 
     */
    public String getLockPassword() {
        return lockPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.lock_password
     *
     * @param lockPassword the value for core_article.lock_password
     *
     * 
     */
    public void setLockPassword(String lockPassword) {
        this.lockPassword = lockPassword == null ? null : lockPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.is_draft
     *
     * @return the value of core_article.is_draft
     *
     * 
     */
    public Boolean getIsDraft() {
        return isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.is_draft
     *
     * @param isDraft the value for core_article.is_draft
     *
     * 
     */
    public void setIsDraft(Boolean isDraft) {
        this.isDraft = isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.labels
     *
     * @return the value of core_article.labels
     *
     * 
     */
    public String getLabels() {
        return labels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.labels
     *
     * @param labels the value for core_article.labels
     *
     * 
     */
    public void setLabels(String labels) {
        this.labels = labels == null ? null : labels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.cust_uri
     *
     * @return the value of core_article.cust_uri
     *
     * 
     */
    public String getCustUri() {
        return custUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.cust_uri
     *
     * @param custUri the value for core_article.cust_uri
     *
     * 
     */
    public void setCustUri(String custUri) {
        this.custUri = custUri == null ? null : custUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.comment_type
     *
     * @return the value of core_article.comment_type
     *
     * 
     */
    public Integer getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.comment_type
     *
     * @param commentType the value for core_article.comment_type
     *
     * 
     */
    public void setCommentType(Integer commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_article.is_special
     *
     * @return the value of core_article.is_special
     *
     * 
     */
    public Boolean getIsSpecial() {
        return isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_article.is_special
     *
     * @param isSpecial the value for core_article.is_special
     *
     * 
     */
    public void setIsSpecial(Boolean isSpecial) {
        this.isSpecial = isSpecial;
    }
}