package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
public class CoreGossip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.type
     * 1，文本；2，带图片的文本
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.content
     *
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.img_url
     *
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.add_time
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_gossip.star_number
     *
     */
    private Integer starNumber;
}