package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

/**
 * @author BlueSkyCarry
 */
@Getter
@Setter
@NoArgsConstructor
public class CoreArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.menu_id
     *
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.title
     *
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.content
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.is_show_title
     *
     */
    private Boolean isShowTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.abstract_msg
     *
     */
    private String abstractMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.create_time
     *
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.update_time
     *
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.is_lock
     *
     */
    private Boolean isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.lock_password
     *
     */
    private String lockPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.is_draft
     *
     */
    private Boolean isDraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.labels
     *
     */
    private String labels;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.cust_uri
     *
     */
    private String custUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.comment_type
     *
     */
    private Integer commentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_article.is_special
     *
     */
    private Boolean isSpecial;
}