package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import top.reminisce.coolnetblogcore.pojo.ao.Tree;

import java.util.Date;

/**
 * 菜单实体 sql
 * @author BlueSkyCarry
 */
@Getter
@Setter
@NoArgsConstructor
public class CoreMenu extends Tree<CoreMenu> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.name
     *
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.pId
     *
     */
     private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.is_home
     *
     */
    private Boolean isHome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.order_number
     *
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.is_show
     *
     */
    private Boolean isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.tips
     *
     */
    private String tips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.update_time
     *
     */
    private Date updateTime;
}