package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import top.reminisce.coolnetblogcore.pojo.ao.Tree;

import java.util.Date;

/**
 * 菜单实体 sql
 * @author BlueSkyCarry
 */
@Getter
@Setter
@NoArgsConstructor
public class CoreMenu extends Tree<CoreMenu> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.name
     *
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.pId
     *
     */
     private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.is_home
     *
     */
    private Boolean isHome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.order_number
     *
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.is_show
     *
     */
    private Boolean isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.tips
     *
     */
    private String tips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_menu.update_time
     *
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.id
     *
     * @return the value of core_menu.id
     *
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.id
     *
     * @param id the value for core_menu.id
     *
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.name
     *
     * @return the value of core_menu.name
     *
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.name
     *
     * @param name the value for core_menu.name
     *
     * 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.pId
     *
     * @return the value of core_menu.pId
     *
     * 
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.pId
     *
     * @param pid the value for core_menu.pId
     *
     * 
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.is_home
     *
     * @return the value of core_menu.is_home
     *
     * 
     */
    public Boolean getIsHome() {
        return isHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.is_home
     *
     * @param isHome the value for core_menu.is_home
     *
     * 
     */
    public void setIsHome(Boolean isHome) {
        this.isHome = isHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.order_number
     *
     * @return the value of core_menu.order_number
     *
     * 
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.order_number
     *
     * @param orderNumber the value for core_menu.order_number
     *
     * 
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.is_show
     *
     * @return the value of core_menu.is_show
     *
     * 
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.is_show
     *
     * @param isShow the value for core_menu.is_show
     *
     * 
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.tips
     *
     * @return the value of core_menu.tips
     *
     * 
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.tips
     *
     * @param tips the value for core_menu.tips
     *
     * 
     */
    public void setTips(String tips) {
        this.tips = tips == null ? null : tips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_menu.update_time
     *
     * @return the value of core_menu.update_time
     *
     * 
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_menu.update_time
     *
     * @param updateTime the value for core_menu.update_time
     *
     * 
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}