package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
public class CoreFilePath {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.file_rel_path
     *
     */
    private String fileRelPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.help_name
     *
     */
    private String helpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.upload_time
     *
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.file_type
     *
     */
    private String fileType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_file_path.id
     *
     * @return the value of core_file_path.id
     *
     * 
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_file_path.id
     *
     * @param id the value for core_file_path.id
     *
     * 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_file_path.file_rel_path
     *
     * @return the value of core_file_path.file_rel_path
     *
     * 
     */
    public String getFileRelPath() {
        return fileRelPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_file_path.file_rel_path
     *
     * @param fileRelPath the value for core_file_path.file_rel_path
     *
     * 
     */
    public void setFileRelPath(String fileRelPath) {
        this.fileRelPath = fileRelPath == null ? null : fileRelPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_file_path.help_name
     *
     * @return the value of core_file_path.help_name
     *
     * 
     */
    public String getHelpName() {
        return helpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_file_path.help_name
     *
     * @param helpName the value for core_file_path.help_name
     *
     * 
     */
    public void setHelpName(String helpName) {
        this.helpName = helpName == null ? null : helpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_file_path.upload_time
     *
     * @return the value of core_file_path.upload_time
     *
     * 
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_file_path.upload_time
     *
     * @param uploadTime the value for core_file_path.upload_time
     *
     * 
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_file_path.file_type
     *
     * @return the value of core_file_path.file_type
     *
     * 
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_file_path.file_type
     *
     * @param fileType the value for core_file_path.file_type
     *
     * 
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }
}