package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
public class CoreFilePath {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.file_rel_path
     *
     */
    private String fileRelPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.help_name
     *
     */
    private String helpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.upload_time
     *
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_file_path.file_type
     *
     */
    private String fileType;
}