package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
public class CoreFieldMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_field_map.field_name
     *
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_field_map.value
     *
     */
    private Integer value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_field_map.text
     *
     */
    private String text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_field_map.field_name
     *
     * @return the value of core_field_map.field_name
     *
     * 
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_field_map.field_name
     *
     * @param fieldName the value for core_field_map.field_name
     *
     * 
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_field_map.value
     *
     * @return the value of core_field_map.value
     *
     * 
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_field_map.value
     *
     * @param value the value for core_field_map.value
     *
     * 
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_field_map.text
     *
     * @return the value of core_field_map.text
     *
     * 
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_field_map.text
     *
     * @param text the value for core_field_map.text
     *
     * 
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }
}