package top.reminisce.coolnetblogcore.pojo.po.sql;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
public class CoreLoveLook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.id
     *
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.add_time
     *
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.rel_href
     *
     */
    private String relHref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.link_type
     *
     */
    private Integer linkType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_love_look.link_name
     *
     */
    private String linkName;
}